[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
startCommand = "/app/start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
